[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[character]
symbol = "âœ"

[cmd_duration]
min_time = 500

# [time]
# disabled = false
# format = "ğŸ•™[ %T ]"
# utc_time_offset = +10
